name: Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black==23.12.1

    - name: Run tests
      run: |
        python -m pytest tests/ -k "not test_parse_arguments" -v

    - name: Check code style
      run: |
        flake8 . --count --exit-zero --max-line-length=88 --exclude=venv
        black --check --line-length=88 .

    - name: Test specific imports
      run: |
        echo "Testing specific module imports..."
        cd atari/baselines
        python -c "from atari_baseline_train import parse_arguments"
        python -c "from atari_baseline_test import parse_arguments"
        echo "All module imports successful"
